# Site settings
title: Genomics Platform
theme: jekyll-theme-merlot
email:
description: reNEW, CPR, ICMM
baseurl:
url:
twitter_username:
github_username: DanStemGenomics

# Build settings
markdown: kramdown
permalink: pretty
